export const developerInfo = {
  name: "Md. Shohag Kaisar",
  role: "WordPress Developer | MERN Stack Developer | Next.js Developer",
  location: "Gazipur, Bangladesh",
  email: "shohagkaisar@gmail.com",
  phone: "+8801677056327",
  social: {
    facebook: "https://www.facebook.com/shohag.kaisar.9/",
    github: "https://github.com/ShohagKaisar",
    linkedin: "https://www.linkedin.com/in/shohag-kaisar",
    whatsapp: "https://wa.me/8801677056327?text=Hi%20Shohag!%20I%20visited%20your%20portfolio.",
  },
  profileImage: "/profile.jpg",
};

export const techStack = {
  frontend: [
    { name: "HTML5", icon: "html" },
    { name: "CSS3", icon: "css" },
    { name: "JavaScript", icon: "javascript" },
    { name: "TypeScript", icon: "typescript" },
    { name: "React", icon: "react" },
    { name: "Next.js", icon: "nextjs" },
    { name: "Tailwind CSS", icon: "tailwind" },
    { name: "Bootstrap", icon: "bootstrap" },
    { name: "Redux", icon: "redux" },
  ],
  backend: [
    { name: "Node.js", icon: "nodejs" },
    { name: "Express.js", icon: "express" },
    { name: "REST API", icon: "api" },
    { name: "GraphQL", icon: "graphql" },
    { name: "NestJS", icon: "nestjs" },
    { name: "FastAPI", icon: "fastapi" },
  ],
  wordpress: [
    { name: "WordPress", icon: "wordpress" },
    { name: "WooCommerce", icon: "woocommerce" },
    { name: "ACF Pro", icon: "acf" },
    { name: "Elementor", icon: "elementor" },
    { name: "Gutenberg", icon: "gutenberg" },
    { name: "WP REST API", icon: "wpapi" },
    { name: "Custom Themes", icon: "theme" },
    { name: "Custom Plugins", icon: "plugin" },
    { name: "CPT UI", icon: "cptui" },
    { name: "WP CLI", icon: "wpcli" },
    { name: "Yoast SEO", icon: "yoast" },
    { name: "Contact Form 7", icon: "cf7" },
  ],
  database: [
    { name: "MySQL", icon: "mysql" },
    { name: "PostgreSQL", icon: "postgresql" },
    { name: "MongoDB", icon: "mongodb" },
    { name: "Firebase", icon: "firebase" },
    { name: "Supabase", icon: "supabase" },
    { name: "Prisma", icon: "prisma" },
    { name: "TypeORM", icon: "typeorm" },
    { name: "Mongoose", icon: "mongoose" },
    { name: "Doctrine", icon: "doctrine" },
  ],
  tools: [
    { name: "Git", icon: "git" },
    { name: "GitHub", icon: "github" },
    { name: "Docker", icon: "docker" },
    { name: "Webpack", icon: "webpack" },
    { name: "Vite", icon: "vite" },
    { name: "Figma", icon: "figma" },
    { name: "VS Code", icon: "vscode" },
    { name: "Postman", icon: "postman" },
    { name: "npm", icon: "npm" },
    { name: "Linux", icon: "linux" },
    { name: "AWS", icon: "aws" },
    { name: "Vercel", icon: "vercel" },
    { name: "Netlify", icon: "netlify" },
    { name: "Cloudflare", icon: "cloudflare" },
    { name: "CI/CD", icon: "cicd" },
  ],
  others: [
    { name: "Networking", icon: "networking" },
    { name: "Server Management", icon: "server" },
  ],
};

export const projects = [
  {
    title: "ZAHRA Jewelry Website",
    description:
      "A dynamic movie browsing portal with search functionality, detailed movie information, and responsive design. Built with modern web technologies for optimal performance ZAHRA Jewelry is a premium, modern e-commerce website designed for a luxury jewelry brand. The website focuses on creating an elegant and trustworthy shopping experience while showcasing jewelry collections with high-quality visuals, refined typography, and a clean luxury aesthetic. user experience.",
    tags: ["React", "Next.js", "API", "TailwindCSS", "Responsive"],
    image: "/jewelry.jpg",
    liveUrl: "https://jewelry-website-alpha.vercel.app/",
    color: "from-violet-500/20 to-purple-500/20",
  },
  {
    title: "Go Green Tours & Travels",
    description:
      "The website features an engaging adventure-focused homepage with destination search, travel-date selection, featured tour packages, traveler statistics, customer testimonials, secure booking messaging, travel deals, and newsletter subscription. It emphasizes eco-friendly tourism, expert local guides, competitive pricing, 24/7 support, secure booking, and flexible cancellation to create a trustworthy travel-booking experience.",
    tags: ["Next.js", "React.js", "TypeScript", "Tailwind CSS", "Framer Motion", "Lucide React", "Next.js Image Optimization", "Responsive Design"],
    image: "/tour.jpg",
    liveUrl: "https://gogreen-tours-travels.vercel.app/",
    color: "from-amber-500/20 to-orange-500/20",
  },
  {
    title: "Doctor Apointment Website",
    description:
      "Doctor Appointment Website is a modern healthcare appointment management platform designed to make it easy for patients to discover doctors, explore medical specialties, check availability, and book appointments online. The platform provides a clean, trustworthy, and responsive experience for patients while helping doctors efficiently manage their schedules and appointments.",
    tags: ["Next.js",
      "React.js",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Prisma",
      "REST API",
      "JWT Authentication",
      "Stripe",
      "Lucide React"],
    image: "/doctor-apointment.jpg",
    liveUrl: "https://doctor-appointment-system-olive.vercel.app/",
    color: "from-emerald-500/20 to-teal-500/20",
  },
  {
    title: "Restaurant Website",
    description:
      "A modern and responsive restaurant website designed to provide an engaging online dining experience. The website showcases the restaurant’s menu, food items, services, special offers, location, and contact information with a clean and attractive UI. Customers can easily explore the menu, view featured dishes, make reservations, and get in touch with the restaurant. Built with modern web technologies for fast performance, smooth animations, mobile responsiveness, and an intuitive user experience.",
    tags: ["Next.js",
      "React.js",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Prisma",
      "REST API",
      "JWT Authentication",
      "Stripe",
      "Lucide React"],
    image: "/restaurent.jpg",
    liveUrl: "https://restaurant-website-lyart-chi.vercel.app/",
    color: "from-rose-500/20 to-pink-500/20",
  },
];

export const experiences = [
  {
    title: "Senior System Engineer",
    company: "Satellite Connection",
    period: "2014 - 2021",
    description:
      "Led enterprise IT infrastructure and system engineering operations, managing Windows and Linux server environments, enterprise networks, virtualization, backup systems, and IT security. Designed, implemented, and maintained scalable network infrastructure using MikroTik and Cisco technologies while managing Active Directory, DNS, DHCP, VPN, firewall policies, and user access controls. Monitored system performance, resolved critical infrastructure issues, implemented backup and disaster recovery strategies, and maintained high availability with a strong focus on security, reliability, and operational continuity.",
    skills: [
      "Windows Server",
      "Linux Server",
      "Active Directory",
      "MikroTik",
      "Cisco Networking",
      "TCP/IP & Routing",
      "DNS & DHCP",
      "VPN & Firewall",
      "Virtualization",
      "Backup & Disaster Recovery",
      "Network Security",
      "System Monitoring",
      "Server Management",
      "IT Infrastructure",
    ],
  },

  {
    title: "IT Manager",
    company: "Handicraft Beauty & Fashion Ltd.",
    period: "2021 - Present",
    description:
      "Manage end-to-end IT operations and infrastructure, overseeing network administration, server management, system security, hardware and software deployment, technical support, and IT asset management. Develop and maintain reliable IT solutions aligned with organizational requirements, troubleshoot complex infrastructure issues, coordinate technical projects, and ensure secure and uninterrupted business operations. Provide technical leadership while implementing best practices for network performance, security, system availability, and operational efficiency.",
    skills: [
      "IT Operations Management",
      "Network Administration",
      "Server Management",
      "IT Infrastructure",
      "Network Security",
      "MikroTik",
      "Cisco",
      "Windows Server",
      "System Troubleshooting",
      "Hardware & Software Management",
      "IT Asset Management",
      "Technical Support",
      "Backup & Recovery",
      "System Monitoring",
    ],
  },

  {
    title: "Full Stack Web Developer",
    company: "Web Application Development",
    period: "2018 - Present",
    description:
      "Design and develop modern, scalable, and responsive web applications using full-stack JavaScript technologies. Build high-performance frontend interfaces with React.js, Next.js, TypeScript, Tailwind CSS, and modern UI libraries while developing secure and scalable backend systems using Node.js, Express.js, REST APIs, and database technologies. Handle complete application development lifecycle including architecture, database design, authentication, API integration, third-party services, performance optimization, deployment, and production maintenance.",
    skills: [
      "React.js",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "Express.js",
      "REST API",
      "MongoDB",
      "PostgreSQL",
      "Prisma",
      "Firebase",
      "Tailwind CSS",
      "Responsive Web Design",
      "Authentication & Authorization",
      "API Integration",
      "Git & GitHub",
      "Vercel Deployment",
      "Performance Optimization",
      "SEO",
    ],
  },

  {
    title: "WordPress Developer",
    company: "WordPress Development & Customization",
    period: "2017 - Present",
    description:
      "Develop, customize, and maintain professional WordPress websites for businesses, organizations, and e-commerce platforms. Build custom websites and landing pages using WordPress, Elementor, WooCommerce, and custom themes while implementing advanced functionality through custom PHP, JavaScript, CSS, and API integrations. Optimize websites for performance, security, SEO, responsiveness, and usability, including WooCommerce customization, payment gateway integration, plugin configuration, website migration, troubleshooting, and ongoing maintenance.",
    skills: [
      "WordPress",
      "WooCommerce",
      "Elementor",
      "Custom Theme Development",
      "Theme Customization",
      "Plugin Customization",
      "PHP",
      "JavaScript",
      "HTML5",
      "CSS3",
      "REST API",
      "Payment Gateway Integration",
      "WordPress Security",
      "Website Migration",
      "Performance Optimization",
      "SEO",
      "Responsive Design",
      "Website Maintenance",
    ],
  },
];

export const education = [
  {
    degree: "Bachelor of Science",
    field: "Computer Science & Engineering",
    institution: "Sonargaon University",
    period: "2012 - 2016",
    description:
      "Studied core computer science fundamentals including data structures, algorithms, database management, software engineering, and networking.",
  },
];

export const skills = [
  { name: "HTML & CSS", level: 95 },
  { name: "JavaScript", level: 90 },
  { name: "React & Next.js", level: 88 },
  { name: "Node.js & Express", level: 85 },
  { name: "Database", level: 82 },
  { name: "Tailwind CSS", level: 92 },
  { name: "WordPress", level: 90 },
  { name: "Networking", level: 87 },
];
